local CELL_SIZE = 100

function init(self)
	self.selected = false
	self.position = go.get_position()

	msg.post(".", "acquire_input_focus")
end

function on_input(self, action_id, action)
	if action_id == hash("select_character") and action.pressed then
		local mouse_x, mouse_y = action.x, action.y
		if (math.abs(mouse_x - self.position.x) < CELL_SIZE / 2) and 
		(math.abs(mouse_y - self.position.y) < CELL_SIZE / 2) then
			self.selected = true
		else
			self.selected = false
		end
	end
end
